---
- name: add hostname and server(ntp, snmp, syslog)
  hosts: ax
  gather_facts: no
  
  vars:
  - ansible_connection: network_cli
  - ansible_network_os: ax
  - ansible_become: yes
  - ansible_become_method: enable
  - ansible_become_pass: 'secret2230'

  tasks:
  - name: configure hostname
    ax_config:
      lines:
        - 'hostname AX2230'
      save_when: changed

  - name: configure ntp server
    ax_config:
      lines:
        - 'ntp client server {{ item }}'
      save_when: changed
    with_items: '{{ ntp.server }}'

  - name: configure snmp community
    ax_config:
      lines:
        - 'snmp-server community {{ item.name }} {{ item.auth }}'
      save_when: changed
    with_items: '{{ snmp.community }}'
  
  - name: configure syslog server
    ax_config:
      lines:
        - 'logging host {{ item }}'
      save_when: changed
    with_items: '{{ syslog.server }}'
