---
- name: save show commands output to localfile
  hosts: ax
  gather_facts: no

  vars:
  - ansible_connection: network_cli
  - ansible_network_os: ax
  - os_version: "2.9"

  tasks:
  - name: execute show commands
    ax_command:
      commands:
        - show version
    register: result
  
  - name: check S/W version
    assert:
      that: "'{{ os_version }}' in '{{ result.stdout_lines[0][2] }}'"
      fail_msg: "ax s/w version is not '{{ os_version }}'"
