---
- name: set initial configuration from console using SmartCS
  hosts: smartcs
  
  vars:
  - ansible_connection: network_cli
  - ansible_network_os: ax
  - ansible_become: yes
  - ansible_become_method: enable
  - ansible_become_pass: 'secret2230'
  - ansible_user: "port01"
  - ansible_password: "secret01"
  - ansible_port: 9301

  tasks:
  - name: set ipaddr to intarface vlan 1
    ax_config:
      lines:
        - 'ip address 192.168.128.2 255.255.255.0'
      parents: interface vlan 1
      save_when: changed
  
  - name: intarface up
    ax_config:
      lines:
        - 'no shutdown'
      parents: interface gigabitethernet 0/1
      save_when: changed
  
  - name: enable ssh 
    ax_config:
      lines:
        - 'ip ssh'
        - 'line vty 0 1'
      save_when: changed
